#!/usr/bin/env bash

# Solana Validator Node - Setup Log Rotation Script
# Configures logrotate to automatically manage validator logs

set -euo pipefail

# Colors for output
readonly RED='\033[0;31m'
readonly GREEN='\033[0;32m'
readonly YELLOW='\033[1;33m'
readonly BLUE='\033[0;34m'
readonly NC='\033[0m'

# Script directory
readonly SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"

# Load configuration
if [ -f "$REPO_ROOT/configs/config.env" ]; then
    source "$REPO_ROOT/configs/config.env"
else
    echo -e "${RED}Error: config.env not found${NC}"
    exit 1
fi

# Logging functions
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

echo "=========================================="
echo "Solana Validator - Log Rotation Setup"
echo "=========================================="
echo ""

# Check if running as root (required for logrotate setup)
if [ "$EUID" -ne 0 ]; then
    log_error "This script must be run as root (use sudo)"
    echo ""
    echo "Run: sudo $0"
    exit 1
fi

# Check if logrotate is installed
if ! command -v logrotate > /dev/null; then
    log_error "logrotate is not installed"
    echo ""
    echo "Install it with:"
    echo "  Ubuntu/Debian: sudo apt-get install logrotate"
    echo "  RHEL/CentOS: sudo yum install logrotate"
    exit 1
fi

log_success "logrotate is installed"

# Get current user (from config or environment)
if [ -n "${SUDO_USER:-}" ]; then
    LOG_USER="$SUDO_USER"
elif [ -n "${USER:-}" ]; then
    LOG_USER="$USER"
else
    LOG_USER="solana"
fi

# Get user's home directory
if [ "$LOG_USER" = "root" ]; then
    log_error "Cannot determine user. Please run as: sudo -u solana $0"
    exit 1
fi

LOG_USER_HOME=$(eval echo ~$LOG_USER)

# Determine validator log directory
if [ -n "${REPO_ROOT:-}" ]; then
    VALIDATOR_LOG_DIR="$REPO_ROOT/logs"
else
    VALIDATOR_LOG_DIR="$LOG_USER_HOME/Solana-Validator-Node/logs"
fi

log_info "User: $LOG_USER"
log_info "Log directory: $VALIDATOR_LOG_DIR"

# Create logrotate config file
LOGROTATE_CONFIG="/etc/logrotate.d/solana-validator"
LOGROTATE_SOURCE="$REPO_ROOT/configs/logrotate-solana-validator.conf"

# Update the config file with actual paths
log_info "Creating logrotate configuration..."

# Create temp config with correct paths
TEMP_CONFIG=$(mktemp)
cat > "$TEMP_CONFIG" <<EOF
# Logrotate configuration for Solana Validator
# Auto-generated by setup-log-rotation.sh
# User: $LOG_USER
# Log directory: $VALIDATOR_LOG_DIR

$VALIDATOR_LOG_DIR/validator.log {
    daily
    rotate 3
    compress
    delaycompress
    missingok
    notifempty
    create 0644 $LOG_USER $LOG_USER
    maxsize 50M
    copytruncate
}

$VALIDATOR_LOG_DIR/*.log {
    weekly
    rotate 2
    compress
    delaycompress
    missingok
    notifempty
    create 0644 $LOG_USER $LOG_USER
    maxsize 10M
}
EOF

# Copy to logrotate directory
cp "$TEMP_CONFIG" "$LOGROTATE_CONFIG"
chmod 644 "$LOGROTATE_CONFIG"
rm "$TEMP_CONFIG"

log_success "Logrotate configuration created: $LOGROTATE_CONFIG"

# Test logrotate configuration
log_info "Testing logrotate configuration..."
if logrotate -d "$LOGROTATE_CONFIG" > /dev/null 2>&1; then
    log_success "Logrotate configuration is valid"
else
    log_warning "Could not test logrotate configuration (may still work)"
fi

# Show configuration summary
echo ""
echo "=========================================="
log_success "Log Rotation Configuration Summary"
echo "=========================================="
echo ""
echo "Configuration file: $LOGROTATE_CONFIG"
echo ""
echo "Settings:"
echo "  - validator.log:"
echo "    • Rotates: Daily"
echo "    • Keeps: 3 days"
echo "    • Max size: 50MB (rotates immediately if exceeded)"
echo "    • Compression: Enabled (delayed)"
echo ""
echo "  - Other logs (*.log):"
echo "    • Rotates: Weekly"
echo "    • Keeps: 2 weeks"
echo "    • Max size: 10MB"
echo "    • Compression: Enabled (delayed)"
echo ""
echo "Log rotation will run automatically via cron (usually daily)"
echo ""
echo "To test rotation manually:"
echo "  sudo logrotate -f $LOGROTATE_CONFIG"
echo ""
echo "To view rotation status:"
echo "  sudo logrotate -d $LOGROTATE_CONFIG"
echo ""

log_success "Log rotation setup complete!"

